apiVersion: v1
kind: Service
metadata:
  name: hotrod
  labels:
    app: hotrod
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hotrod

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: hotrod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - name: hotrod
        image: docker.io/rnburn/hotrod:latest
        ports:
        - containerPort: 8080
        env:
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hotrod
spec:
  backend:
    serviceName: hotrod
    servicePort: 8080
